version: 2.1

jobs:
  build:
    machine: true  # Use a full VM instead of Docker
    steps:
      - checkout
      - run:
          name: Clean Existing Dependencies
          command: rm -rf node_modules yarn.lock package-lock.json
      - run:
          name: Install Dependencies
          command: npm install --frozen-lockfile
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    machine: true  # Use a full VM
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Azure Server
          command: |
            ssh -o StrictHostKeyChecking=no brampton@api.trim.codes "bash -c '
              cd trim/core-backend &&
              git clean -fd &&          # Remove untracked files
              git pull origin main  &&  # Pull changes safely
              rm -rf node_modules yarn.lock package-lock.json &&
              npm install --frozen-lockfile &&
              npm run build &&
              pm2 restart trim-api
            '"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
