version: 2.1

jobs:
  build:
    machine: true  # Use a full VM instead of Docker
    steps:
      - checkout
      - run:
          name: Clean Existing Dependencies
          command: rm -rf node_modules yarn.lock package-lock.json
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    machine: true  # Use a full VM
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Azure Server
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
              cd /var/www/trim-api
              git pull origin main
              rm -rf node_modules yarn.lock package-lock.json
              yarn install --frozen-lockfile
              yarn build
              pm2 restart trim-api
            EOF

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
